config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #Pages
  root to: 'pages#index'
  get 'users_index', to: 'pages#users_index', as: 'users_index'
  get 'test_page', to: 'pages#test_page', as: 'test_page'
  get 'user_table', to: 'pages#user_table', as: 'user_table'

  #Users
  post 'create_user', to: 'users#create', as: 'create_user'
  post 'clear_users', to: 'users#clear', as: 'clear_users'
  post 'modify_users', to: 'users#modify', as: 'modify_users'






end

app/views/pages/index.html.erb
<%= render 'pages/index/users' %>

app/views/pages/test_page.html.erb
<div id='create-user' style='text-align:center'><%= link_to 'Home Page', root_path, method: :get %></div>
<div id='create-user' style='text-align:center'><%= link_to 'Create Humans!', create_user_path, method: :post %></div>
<div id='clear-users' style='text-align:center'><%= link_to 'Let nature do its thing!', modify_users_path, method: :post %></div>
<div id='clear-users' style='text-align:center'><%= link_to 'Scorch the Earth!', clear_users_path, method: :post %></div>

<h1>test page</h1>

app/views/pages/user_table.html.erb
<div id='create-user' style='text-align:center'><%= link_to 'Home Page', root_path, method: :get %></div>
<div id='create-user' style='text-align:center'><%= link_to 'Create Humans!', create_user_path, method: :post %></div>
<div id='clear-users' style='text-align:center'><%= link_to 'Let nature do its thing!', modify_users_path, method: :post %></div>
<div id='clear-users' style='text-align:center'><%= link_to 'Scorch the Earth!', clear_users_path, method: :post %></div>

<table class = 'table'>
  <% @users.each do |user| %>
    <tr><td><%= @users[0..4] %></td></tr>
    <tr><td><%= @users[5..9] %></td></tr>
    <tr><td><%= @users[10..14] %></td></tr>
    <tr><td><%= @users[15..19] %></td></tr>
  <% end %>
</table>